"""add sites and page views

Revision ID: 94120d472552
Revises: 4c9f2f945f54
Create Date: 2026-09-05 14:05:12.593907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94120d472552'
down_revision: Union[str, None] = '4c9f2f945f54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('site_key', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_key')
    )
    op.create_table('page_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('referrer', sa.String(length=2000), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('visitor_hash', sa.String(length=64), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('region', sa.String(length=80), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('device_type', sa.String(length=20), nullable=True),
    sa.Column('os', sa.String(length=60), nullable=True),
    sa.Column('browser', sa.String(length=60), nullable=True),
    sa.Column('is_bot', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Every stats query filters by site + date range, or counts distinct visitors
    # within a window — both lean on this index.
    op.create_index('ix_page_views_site_id_created_at', 'page_views', ['site_id', 'created_at'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_page_views_site_id_created_at', table_name='page_views')
    op.drop_table('page_views')
    op.drop_table('sites')
    # ### end Alembic commands ###
