"""add tracking domains and bot redirect url

Revision ID: e279ba90f310
Revises: 3e5dc7d3cb7d
Create Date: 2026-09-03 23:54:32.651899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e279ba90f310'
down_revision: Union[str, None] = '3e5dc7d3cb7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracking_domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('campaigns', sa.Column('tracking_domain_id', sa.Integer(), nullable=True))
    op.add_column('campaigns', sa.Column('bot_redirect_url', sa.String(length=1000), nullable=True))
    op.create_foreign_key(None, 'campaigns', 'tracking_domains', ['tracking_domain_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.drop_column('campaigns', 'bot_redirect_url')
    op.drop_column('campaigns', 'tracking_domain_id')
    op.drop_table('tracking_domains')
    # ### end Alembic commands ###
